upstream hello_django {
    server web:8000;
}

server {
    listen 80;
    checkingtest.net.uz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    https://checkingtest.net.uz;

    ssl_certificate /etc/letsencrypt/live/checkingtest.net.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/checkingtest.net.uz/privkey.pem;

    location / {
        proxy_pass http://hello_django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }
}